import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const links = ["Projects", "Tasks", "User"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen flex flex-col">
          <div className="w-screen bg-gray-900 h-[80px] text-white">
            dfhadshfjkashkfh
          </div>
          <div className="w-screen grow flex flex-row">
            <div className="bg-slate-800 hidden sm:flex sm:flex-col sm:items-center  md:w-1/6 max-w-[200px] min-w-[100px] bg-white-300 grow">
              {links.map((link) => (
                <Link
                  href={`/${link}`}
                  className="text-white h-[50px] flex text-center justify-center items-center w-[80%] text-sm mt-5 font-mono hover:bg-slate-500 rounded-md"
                >
                  {link}
                </Link>
              ))}
            </div>
            <div className="grow bg-slate-700 h-full"> {children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
